# Generated by Django 2.2.5 on 2019-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrers',
            name='count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
