# Generated by Django 2.2.5 on 2019-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_referrers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claps',
            name='page_url',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagecounts',
            name='page_url',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referrers',
            name='page_url',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useragents',
            name='user_agent',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
