# Generated by Django 2.2.5 on 2019-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190929_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrers',
            name='page_url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='referrers',
            unique_together={('page_url', 'referrer')},
        ),
    ]
